/*
 * This include file describes the formatting of Amiga DOS floppies,
 * at what would usually be the hardware level.
 */


/*
 * Disk info. which is not dependant on any particular disk format.
 * Note, you shouldn't count on being able to get more than TRKUSED
 * bytes per track, but you might get (and hence must read and write)
 * as many as TRKUSED + TRKSLOP.
 */
#define	RECSLOP		20		/* extra steps for recalibrate */
#define	TRACKS		160		/* number of tracks per disk */
#define	TRKPCYL		2		/* tracks per cylinder */
#define	TRKUSED		11968		/* max. bytes to use per track */
#define	TRKSLOP		1660		/* possible extra bytes on track */


/*
 * Information specific to Amiga DOS layout.
 */
#define	NSEC	11			/* sectors per track */
#define	BPSEC	512			/* data bytes per sector */
#define	TRKRLEN	(TRKUSED + TRKSLOP + sizeof(mfmsec))
#define	TRKWLEN	(TRKUSED + TRKSLOP + sizeof(ushort))
#define	TRKBLEN	(TRKRLEN + 16)		/* size of track buff (with slop) */
#define	CHKLEN	(2*sizeof(mfmsec) + TRKSLOP)
#define	SECOK	0xFF			/* sector-ok magic value */


/*
 * Mfmsec describes the layout of a sector which is MFM encoded.
 *	magic is always AAAA AAAA 4489 4489.  Note, this is unmistakable
 *		because it isn't legal MFM.
 *	id is the sector/track id word.
 *	label is a label used in disk recovery (?).
 *	hdrchk is a checksum of the id and label.
 *	datachk is a checksum of data.
 * Note, each individual field (except for magic) should be decoded
 * as one block.
 * The MFM encoding of a block of length n consists of two blocks of
 * length n:
 *	First a block of all the odd data bits shifted right one bit
 *		with intervening clock bits.
 *	Second a block of all the even data bits with intervening clock
 *		bits.
 * The clock bits are generated by the rule that a clock bit is a 1
 * iff the two adjacent data bits are both 0.
 */
typedef struct	mfmsec {
	ushort	magic[4],
		id[4],
		label[16],
		hdrchk[4],
		datachk[4],
		data[BPSEC];
}	mfmsec;


/*
 * Sechdr describes the layout of a sector header after it is MFM decoded,
 * not including the magic member of msmsec or the actual data.
 * Checksums consist of first xoring longs together, then xoring the
 * result with itself shifted one bit right, and finally anding this
 * with 0x55555555.  Note that despite the similarity of this mask
 * with what is used in MFM decoding, the two are actually not logically
 * related.
 * Note, ord is the number of sectors, from the current one, up through
 * the last one written.  After that, you will have to resyncronize.
 */
typedef struct	sechdr {
	uchar	magic,			/* always SECOK */
		trk,			/* track number [0, TRACKS) */
		sec,			/* sector number [0, NSEC) */
		ord,			/* write number (0, NSEC] */
		label[16];		/* helps trashed disk recov. (?) */
	ulong	hdrchk,			/* checksum of above */
		datachk;		/* checksum of below */
}	sechdr;
